apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "petclinic"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "petclinic"
    spec:
      containers:
        - name: "petclinic"
          image: "myfirstprivateregistry.azurecr.io/petclinic"
          ports:
          - containerPort: 8080